CREATE TABLE IF NOT EXISTS "Customer" (
  id SERIAL PRIMARY KEY,
  customer_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Reservations" (
  id SERIAL PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES "Customer"(id) ON DELETE CASCADE,
  reservation_time TIMESTAMP NOT NULL,
  number_of_guests INTEGER NOT NULL CHECK (number_of_guests > 0),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
